# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'uploadfile-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for uploadfile-ios

  target 'uploadfile-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'uploadfile-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'Kingfisher'

end
